### ISSUE TITLE
Showcase in Readme

### ISSUE THREAD

**Issue by expacc007** [mov-cli/mov-cli#11]
1. I couldn't figure out how to use it, adding a showcase in readme would help newcomers to get started.
Example: https://github.com/pystardust/ani-cli#showcase.

2. Whats my mistake?
```
Please name the movie/series with the provider, ex: theflix: spiderman theflix
Sorry, I don't know that provider
```

**Comment by Poseidon444** [comment]
Will be added

**Comment by expacc007** [comment]
What about second question?

**Comment by Poseidon444** [comment]
when it asks the provider you name only the provider.
then it'll ask you the name of the movie
![image](https://user-images.githubusercontent.com/87462580/172375603-d5f85a8b-7da6-4983-8802-0c73d9306af2.png)

**Comment by expacc007** [comment]
It says "Please name the movie/series with the provider, ex: theflix:"
Thats misleading rather it should ask "Please name the provider, ex: theflix:" if it only needs the provider in the first prompt.

**Comment by Poseidon444** [comment]
Right, that's my bad. I'll fix it in the next commit

**Comment by swapdub** [comment]
I recently started using this, and may I suggest instead of making a user type the provider's name, make it numbered as you have for the movie list?
Pros (imo) :
- This only supports limited providers, no point keeping it open-ended
- Reduces the chance of a typo (and hence user frustration)

PS: If you think that's worth doing can I make a pull request? (are there any contribution rules? I am still learning on how to contribute)

**Comment by Poseidon444** [comment]
The project is currently going through a lot of changes. I would suggest making a pull after a week or so.

**Comment by Poseidon444** [comment]
The project is currently going through a lot of changes. I would suggest making a pull after a week or so.

**Comment by ghost** [comment]
#35
