### ISSUE TITLE
[FEATURE] Show season/episode list instead of search

### ISSUE THREAD

**Issue by yawnbo** [mov-cli/mov-cli#211]
**Describe the feature/change you'd like**
For shows with multiple episodes it would be great to be sent to a menu with options such as next episode, previous episode, or replay current instead of being sent back to search after each episode. Even just being sent to the seasons or episode page instead of the search would be amazing.

**Additional context**
ani-cli (https://github.com/pystardust/ani-cli) has a great way of doing this.

**Comment by EbanNox** [comment]
I totaly agree on this, love the way ani-cli doing this... also they have a arg option like "-r 1-100" where it binch watches every episode, besacly start playing episode 1, and when u finnish watching it, it would alrdey scrape and pre prepare episode 2 so that as soon as mpv closes, it launches the next episode, up to 100 if there are that many episode, if I type ( -r "5-32" ) it will start playing episode 5 and then binch it or auto play the next one untill it reaches 32. Or u can type ( -e 4 ) to automaticaly play episode 4, but it wont auto play next episode, instead it returns u to a menue where i can select "next", "prev", "replay" etc.

**Comment by THEGOLDENPRO** [comment]
This will be added. This is the issue you should track --> #226
